# Use the official Node.js image.
FROM node:16

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json.
COPY package*.json ./

# Install the application dependencies.
RUN npm install

# Copy the rest of your application code.
COPY . .

# Expose the port your app runs on (if applicable).
EXPOSE 3000

# Command to run your application.
CMD ["npm", "start"]