import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Providers from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}

interface Route {
  link: string;
  title: string;
}

const routes: Route[] = [
  {
    link: "/",
    title: "Home",
  },
  {
    link: "/posts",
    title: "Posts",
  },
  {
    link: "/delete",
    title: "Delete",
  },
];

function Navbar() {
  return (
    <div className="flex w-full gap-3 bg-rose-500">
      {/* {routes.map((route) => (
        // <>
        //   <Link key={route.title} href={route.link}>{route.title}</Link>
        // </>
      ))} */}
    </div>
  );
}
